#ifndef SIMPLEDATABASEMANAGMENTSYSTEM__AUTHORPRIMARYINDEX_H
#define SIMPLEDATABASEMANAGMENTSYSTEM__AUTHORPRIMARYINDEX_H

#include "Index.cpp"

class PrimaryIndex : Index{
    int ins;
};

#endif //SIMPLEDATABASEMANAGMENTSYSTEM__AUTHORPRIMARYINDEX_H