//
// Created by lap top eur on ١٢/١١/٢٠٢٣.
//

#ifndef SIMPLEDATABASEMANAGMENTSYSTEM__BOOKDATA_H
#define SIMPLEDATABASEMANAGMENTSYSTEM__BOOKDATA_H

#endif //SIMPLEDATABASEMANAGMENTSYSTEM__BOOKDATA_H
