#ifndef SIMPLEDATABASEMANAGMENTSYSTEM__BOOKFILEDATA_H
#define SIMPLEDATABASEMANAGMENTSYSTEM__BOOKFILEDATA_H

#include "../FileError.cpp"
#include "BookHeader.cpp"



#endif //SIMPLEDATABASEMANAGMENTSYSTEM__BOOKFILEDATA_