//
// Created by Fady Lawendy on 07/12/2023.
//
#ifndef SIMPLEDATABASEMANAGMENTSYSTEM__BOOKDATA_H
#define SIMPLEDATABASEMANAGMENTSYSTEM__BOOKDATA_H


#endif //SIMPLEDATABASEMANAGMENTSYSTEM__BOOKDATA_H